name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-16.04
    name: Build & Test
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: "1.15"
      - name: Setup protoc
        uses: arduino/setup-protoc@v1
      - name: Setup protoc-gen-go
        run: |
          go get github.com/golang/protobuf/protoc-gen-go
      - name: Run tests
        run: |
          go generate
          go test ./...
